version: '3.8'

services:
  laravel-app:
    build:
      context: .
      dockerfile: Dockerfile
      target: final
    container_name: laravel-prod
    volumes:
      - ./src:/var/www/html
      - ./logs/apache2:/var/log/apache2
      - ./logs/php:/var/log/php
      - storage-app:/var/www/html/storage/app
      - storage-framework:/var/www/html/storage/framework
      - storage-logs:/var/www/html/storage/logs
    ports:
      - "80:80"
      - "443:443"
    environment:
      - APP_ENV=production
      - APP_DEBUG=false
      - APP_KEY=${APP_KEY}
      - DB_CONNECTION=firebird
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_DATABASE=${DB_DATABASE}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - laravel-network

networks:
  laravel-network:
    driver: bridge

volumes:
  storage-app:
    driver: local
  storage-framework:
    driver: local
  storage-logs:
    driver: local
