version: "3.9"

services:
  laravel:
    build:
      context: ./docker
      dockerfile: Dockerfile
    container_name: laravel-app
    volumes:
      - ./:/var/www/html
    ports:
      - "9005:9000" # php artisan serve padrão em 9000
    working_dir: /var/www/html
    command: sh -c "php artisan serve --host=0.0.0.0 --port=9000"

  composer:
    image: composer:2
    container_name: laravel-composer
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    entrypoint: ["composer"]

